export const FETCH_TRENDING_PENDING = 'FETCH_TRENDING_PENDING';
export const FETCH_TRENDING_SUCCESS = 'FETCH_TRENDING_SUCCESS';
export const FETCH_TRENDING_ERROR = 'FETCH_TRENDING_ERROR';
export const FETCH_PREVIOUS_TRENDING = 'FETCH_PREVIOUS_TRENDING';
